Blazor register
INF-Project-C/star-shl-web pull request #7
Opened 2021-12-05 20:40 UTC by VACEfron

Overgezet naar Blazor WASM en registreren geïmplementeerd. Jezus dat duurde ff. Test pls.

2021-12-06 15:43 UTC, bituq requested changes

2021-12-06 15:43 UTC, bituq commented on SharedModels/SharedModels/AppUser.cs
> +    public class AppUser : IdentityUser
Een lege model?

2021-12-06 15:43 UTC, bituq commented on SharedModels/SharedModels/AuthenticatedUserModel.cs
> +        public string? AccesToken { get; set; }
AccessToken*

2021-12-06 17:02 UTC, VACEfron commented on SharedModels/SharedModels/AppUser.cs
> +    public class AppUser : IdentityUser
Inherit de properties van IdentityUser die worden gebruikt. AppUser is wel onnodig atm maar we kunnen erop uitbreiden wanneer het nodig is I guess.

2021-12-06 17:06 UTC, VACEfron commented on SharedModels/SharedModels/AuthenticatedUserModel.cs
> +        public string? AccesToken { get; set; }
Opgelost door de class te verwijderen, nu het toch niet meer wordt gebruikt

2021-12-07 10:16 UTC, bituq approved these changes

2021-12-07 10:16 UTC, merged